// Generated by CoffeeScript 1.12.7
(function() {
  var ALIGNMENT_RADIUS, BOID_COUNT, Boid, COHESION_RADIUS, SEPARATION_RADIUS,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  paper.install(window);

  ALIGNMENT_RADIUS = 110;

  COHESION_RADIUS = 110;

  SEPARATION_RADIUS = 50;

  BOID_COUNT = 50;

  Boid = (function() {
    function Boid(color) {
      var head, headSymbol, i, j, nextpoint, ref, start;
      if (color == null) {
        color = 'red';
      }
      this.step = bind(this.step, this);
      this.path = new Path();
      this.path.style = {
        strokeWidth: 3,
        strokeCap: 'round',
        strokeColor: color
      };
      head = new Path.Oval([0, 0], [1, 1]);
      head.fillColor = color;
      head.strokeColor = null;
      headSymbol = new paper.Symbol(head);
      this.size = 4;
      this.segments = this.path.segments;
      start = Point.random().multiply(view.size);
      this.direction = Point.random().normalize();
      for (i = j = 0, ref = this.size - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        nextpoint = start.add(new Point(this.direction.x * i * 10, this.direction.y * i * 10));
        this.path.add(nextpoint);
      }
      this.position = start;
    }

    Boid.prototype.step = function(others) {
      var accel, tmpdir;
      accel = this.flock(others);
      tmpdir = this.direction.normalize().multiply(6);
      tmpdir = tmpdir.add(accel.normalize());
      tmpdir = tmpdir.normalize();
      this.direction = tmpdir;
      this.position = this.position.add(this.direction.multiply(3));
      return this.moveTo(this.position);
    };

    Boid.prototype.moveTo = function(point) {
      var angle, i, j, nextSeg, position, ref, vector;
      this.segments[0].point = point;
      for (i = j = 0, ref = this.size - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        nextSeg = this.segments[i + 1];
        position = this.path.segments[i].point;
        angle = (position.subtract(nextSeg.point)).angle;
        vector = new Point({
          angle: angle,
          length: 10
        });
        nextSeg.point = position.subtract(vector);
      }
      return this.path.smooth();
    };

    Boid.prototype.flock = function(others) {
      var alignment, cohesion, edge, separation;
      separation = this.separation(others);
      cohesion = this.cohesion(others);
      cohesion = cohesion.normalize();
      separation = separation.multiply(8);
      alignment = this.alignment(others);
      alignment = alignment.multiply(1);
      edge = this.edgeRepulsion();
      return separation.add(cohesion.add(alignment.add(edge)));
    };

    Boid.prototype.cohesion = function(others) {
      var count, distance, j, len, other, sum;
      count = 0;
      sum = new Point;
      for (j = 0, len = others.length; j < len; j++) {
        other = others[j];
        distance = this.position.getDistance(other.position, false);
        if (distance > 0 && distance < COHESION_RADIUS) {
          sum = sum.add(other.position);
          count++;
        }
      }
      if (count === 0) {
        return sum;
      }
      return this.steerTo(sum.divide(count));
    };

    Boid.prototype.steerTo = function(target) {
      var desired, distance, steer;
      desired = target.subtract(this.position);
      distance = desired.getLength();
      if (distance > 0) {
        steer = desired.subtract(this.direction);
      } else {
        steer = new Vector(0, 0);
      }
      return steer;
    };

    Boid.prototype.separation = function(others) {
      var count, distance, j, len, other, sum, tmp;
      count = 0;
      sum = new Point;
      for (j = 0, len = others.length; j < len; j++) {
        other = others[j];
        distance = this.position.getDistance(other.position, false);
        if (distance > 0 && distance < SEPARATION_RADIUS) {
          tmp = this.position.subtract(other.position);
          tmp = tmp.divide(distance);
          sum = sum.add(tmp);
          count++;
        }
      }
      if (count > 0) {
        sum = sum.divide(count);
      }
      return sum;
    };

    Boid.prototype.alignment = function(others) {
      var count, distance, j, len, other, tmpdirection;
      tmpdirection = new Point;
      count = 0;
      for (j = 0, len = others.length; j < len; j++) {
        other = others[j];
        distance = this.position.getDistance(other.position, false);
        if (distance > 0 && distance < ALIGNMENT_RADIUS) {
          tmpdirection = tmpdirection.add(other.direction);
          count++;
        }
      }
      if (count > 0) {
        tmpdirection = tmpdirection.divide(count);
      }
      return tmpdirection;
    };

    Boid.prototype.edgeRepulsion = function() {
      var center, horizontal, margin, pos, vect, vertical;
      pos = this.position;
      center = view.center;
      horizontal = new Point;
      vertical = new Point;
      margin = Math.min(view.size.width, view.size.height) / 5;
      if (pos.x < margin) {
        horizontal = new Point(margin - pos.x, 0);
      } else if (pos.x > view.size.width - margin) {
        horizontal = new Point(view.size.width - margin - pos.x, 0);
      }
      if (pos.y < margin) {
        vertical = new Point(0, margin - pos.y);
      } else if (pos.y > view.size.height - margin) {
        vertical = new Point(0, view.size.height - margin - pos.y);
      }
      vect = horizontal.add(vertical);
      vect = vect.divide(80);

      /*
      		distance = pos.getDistance center
      		
      		vect = new Point
      		
      		if distance > CENTER_DISTANCE
      			vect = center.subtract pos
      			vect = vect.normalize()
      			vect = vect.multiply (distance - CENTER_DISTANCE)
       */
      return vect;
    };

    return Boid;

  })();

  window.onload = function() {
    var boids, canvas, color, j, ref, x;
    canvas = document.getElementById('canvas');
    paper.setup(canvas);
    console.log("Loaded");
    boids = [];
    for (x = j = 1, ref = BOID_COUNT; 1 <= ref ? j <= ref : j >= ref; x = 1 <= ref ? ++j : --j) {
      color = Color.hsl(x / BOID_COUNT, 1, 0.6);
      boids.push(new Boid(color.hexTriplet()));
    }
    return view.onFrame = function(event) {
      var boid, k, len, results;
      results = [];
      for (k = 0, len = boids.length; k < len; k++) {
        boid = boids[k];
        results.push(boid.step(boids));
      }
      return results;
    };
  };

}).call(this);
